### PR TITLE
Rename structure page to "Leadership" to make more sense

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Structure is a really weird way of putting it IMO.

### CODE REVIEW

**Comment by andrewda** [comment]
I think you'll also need to change this in the navbar config file.

**Comment by evanmhm** [comment]
Should be good now 👍

**Comment by andrewda** [comment]
Although that page is actually the structure of the team, not just leadership .

**Comment by andrewda** [comment]
Like its the page with all the subteam descriptions.

**Comment by evanmhm** [comment]
I agree actually, I just think that theres too many buttons and structure is a little vague, makes navigating the site a little messy (just made #30).

**Comment by SUPERCILEX** [comment]
@andrewda the main goal of the page is showcase our leadership and "structure" doesn't mean anything to me so squashing and merging. Also, I agree with @evanmhm, it's too cluttered and this change makes things clearer.

**Comment by andrewda** [comment]
K makes sense

**Pull request merged**
